---
title: "Data Wrangling"
author: "Emma Freeman"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# These libraries are required in order to run the code in the following r chunks. 

library(tidyverse)
library(dplyr)
library(readr)
library(janitor)
library(stringr)
library(tidycensus)
library(forcats)
library(ggthemes)

```

```{r, include = FALSE}

# I set include = FALSE, so that all of the information about the 
# data being read in is not included when the code is run. This
# information needs not be included after it has been evaluated and 
# the data is wrangled and cleaned

# When confronted with this data, I knew that the column names would
# require extensive cleaning. I first tried to manually change each
# of the column names but found that they had similar prefixes. I 
# decided to us regular expressions and the function 
# str_replace_all to change the column names. In the future I hope 
# to be able to make this into a function as the adjustments to the
# column names for each data set is fairly repetitive. Given that
# I do not have a strong background in function writing in R, I plan # to confer with my TF about the best way to go about this. 

data_2018 <- read_csv("raw-data//2018_college_data.csv") %>%
  clean_names()
names(data_2018) <- str_replace_all(names(data_2018), "^[^_]*_", "")
names(data_2018) <- str_replace_all(names(data_2018), "_of_undergraduate_enrollment_that_are", "")

data_2017 <- read_csv("raw-data//2017_college_data.csv") %>%
  clean_names()
names(data_2017) <- str_replace_all(names(data_2017), "^[^_]*_", "")
names(data_2017) <- str_replace_all(names(data_2017), "_of_undergraduate_enrollment_that_are", "")

data_2016 <- read_csv("raw-data//2016_college_data.csv") %>%
  clean_names()
names(data_2016) <- str_replace_all(names(data_2016), "^[^_]*_", "")
names(data_2016) <- str_replace_all(names(data_2016), "_of_undergraduate_enrollment_that_are", "")

data_2015 <- read_csv("raw-data//2015_college_data.csv") %>%
  clean_names()
names(data_2015) <- str_replace_all(names(data_2015), "^[^_]*_", "")
names(data_2015) <- str_replace_all(names(data_2015), "_of_undergraduate_enrollment_that_are", "")

data_2014 <- read_csv("raw-data//2014_college_data.csv") %>%
  clean_names()
names(data_2014) <- str_replace_all(names(data_2014), "^[^_]*_", "")
names(data_2014) <- str_replace_all(names(data_2014), "_of_undergraduate_enrollment_that_are", "")

data_2013 <- read_csv("raw-data//2013_college_data.csv") %>%
  clean_names()
names(data_2013) <- str_replace_all(names(data_2013), "^[^_]*_", "")
names(data_2013) <- str_replace_all(names(data_2013), "_of_undergraduate_enrollment_that_are", "")

data_2012 <- read_csv("raw-data//2012_college_data.csv") %>%
  clean_names()
names(data_2012) <- str_replace_all(names(data_2012), "^[^_]*_", "")
names(data_2012) <- str_replace_all(names(data_2012), "_of_undergraduate_enrollment_that_are", "")

# For an unknown reason, the level of institution variable was named
# differently than the other data sets. I found this out when I 
# attempted to join this dataset with the other data. This was 
# easily fixed by changing the name of the column

names(data_2012) <- str_replace(names(data_2012), "sector_of_institution", "level_of_institution")

data_2011 <- read_csv("raw-data//2011_college_data.csv") %>%
  clean_names()
names(data_2011) <- str_replace_all(names(data_2011), "^[^_]*_", "")
names(data_2011) <- str_replace_all(names(data_2011), "_of_undergraduate_enrollment_that_are", "")

data_2010 <- read_csv("raw-data//2010_college_data.csv") %>%
  clean_names()
names(data_2010) <- str_replace_all(names(data_2010), "^[^_]*_", "")
names(data_2010) <- str_replace_all(names(data_2010), "_of_undergraduate_enrollment_that_are", "")

# The 2009 data set contained slightly different column names and 
# as such required additional cleaning. 

data_2009 <- read_csv("raw-data//2009_college_data.csv") %>%
  clean_names()
names(data_2009) <- str_replace_all(names(data_2009), "^[^_]*_", "")
names(data_2009) <- str_replace_all(names(data_2009), "1_", "")
names(data_2009) <- str_replace_all(names(data_2009), "_of_undergraduate_enrollment_that_are", "")

```

```{r, include = TRUE}

# I will need to join the data sets about the college demographics 
# from each of the years. Because the data sets have such similar 
# column names, I created a function that would allow me to combine 
# the data sets with less repetition of my code. 

join_data <- function(x, y) {
  full_join(x = x, y = y, by = c("unitid", 
  "name", 
  "year", 
  "undergraduate_enrollment",
  "percent_american_indian_or_alaska_native",
  "percent_asian", 
  "percent_black_or_african_american",
  "percent_hispanic_latino",
  "percent_native_hawaiian_or_other_pacific_islander",
  "percent_white", 
  "percent_two_or_more_races", 
  "percent_race_ethnicity_unknown",
  "percent_nonresident_alien",
  "percent_women",
  "percent_admitted_total",
  "institution_size_category", 
  "state_abbreviation", 
  "level_of_institution", "degree_of_urbanization_urban_centric_locale", 
  "percent_asian_native_hawaiian_pacific_islander")) 
}

# I used the function written above to combine all of the datasets
# except for the 2009 dataset which contains different variables and # information. I will have to decide if adapting the 2009 data will
# be worth it because there are fewer variables included in the 2009
# data.

joined_data <- join_data(data_2018, data_2017)
joined_data <- join_data(joined_data, data_2016)
joined_data <- join_data(joined_data, data_2015)
joined_data <- join_data(joined_data, data_2014)
joined_data <- join_data(joined_data, data_2013)
joined_data <- join_data(joined_data, data_2012)
joined_data <- join_data(joined_data, data_2011)
joined_data <- join_data(joined_data, data_2010)

# write.csv(joined_data, 'joined_data.csv', row.names = F)

# test <- read.csv('joined_data.csv', stringsAsFactors = F)
```
```{r, include = FALSE}
# Last week, I was going to use the census data I had downloaded
# censusdata.gov. Instead I have decided to use the 2010 census data
# included with the tidycensus package because it includes the 
# geometry for map plots.
census_data <- get_decennial(geography = "state", 
                             variables = c(
                               total_pop = "H006001",
                               pop_white = "H006002",
                               pop_african_american = "H006003",
                               pop_native_american_alaskan = "H006004", 
                               pop_asian = "H006005",  pop_native_hawaiian_pacific_islander = "H006006", 
                               pop_other = "H006007", 
                               pop_two_or_more_races = "H006008"), 
                             year = 2010, 
                             geometry = TRUE)
census_data_2 <- get_acs(geography = "us", 
                         variables = c(
                           total_pop = "B01001_001",
                           pop_white = "B01001A_001",
                           pop_african_american = "B01001B_001",
                           pop_native_american_alaskan = "B01001C_001",
                           pop_asian = "B01001D_001",
                           pop_native_hawaiian_pacific_islander = "B01001E_001",
                           pop_other = "B01001F_001",
                           pop_two_or_more_races = "B01001G_001",
                           pop_hispanic = "B01001I_001"),
                         year = 2010) 
census_data_2 <- census_data_2 %>%
  select(variable, estimate) %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  # mutate(pct_white = (pop_white / total_pop) * 100) %>%
  mutate(pct_african_american = (pop_african_american / total_pop) * 100) %>%
  mutate(pct_native_american_alaskan = (pop_native_american_alaskan / total_pop) * 100) %>%
  mutate(pct_asian = (pop_asian / total_pop) * 100) %>%
  mutate(pct_native_hawaiian_pacific_islander = (pop_native_hawaiian_pacific_islander / total_pop) * 100) %>%
  mutate(pct_other = (pop_other / total_pop) * 100) %>%
  mutate(pct_two_or_more_races = (pop_two_or_more_races / total_pop) * 100) %>%
  mutate(pct_hispanic = (pop_hispanic / total_pop) * 100)
# write.csv(census_data_2, 'census.csv', row.names = F)
```



```{r}

# This takes the mean data for the joined_data, so that I can reduce the effect 
# of outliers 
# From there, I created some factor columns to be used in the boxplots in the project

mean_data <- joined_data %>%
  group_by(name) %>%
  mutate(mean_enrollment = mean(undergraduate_enrollment, na.rm = T),
         mean_african_american = mean(percent_black_or_african_american, na.rm = T),
         mean_asian = mean(percent_asian, na.rm = T),
         mean_native = mean(percent_american_indian_or_alaska_native, na.rm = T),
         mean_hispanic = mean(percent_hispanic_latino, na.rm = T),
         mean_pacific = mean(percent_native_hawaiian_or_other_pacific_islander, na.rm = T),
         mean_white = mean(percent_white, na.rm = T),
         mean_two = mean(percent_two_or_more_races, na.rm = T),
         mean_unknown = mean(percent_race_ethnicity_unknown, na.rm = T),
         mean_women = mean(percent_women, na.rm = T),
         mean_admitted = mean(percent_admitted_total, na.rm = T)) %>%
  filter(level_of_institution == "Four or more years") %>%
  mutate(institution_size_category = factor(institution_size_category,
                                            levels = c("Under 1,000",
                                                       "1,000 - 4,999",
                                                       "5,000 - 9,999", 
                                                       "10,000 - 19,999",
                                                       "20,000 and above",
                                                       "Not applicable",
                                                       "Not reported"))) %>%
  filter(institution_size_category != "Not applicable" & institution_size_category != "Not reported") %>%
  mutate(degree_of_urbanization_urban_centric_locale = case_when(str_detect(degree_of_urbanization_urban_centric_locale, "City") ~ "City",
          str_detect(degree_of_urbanization_urban_centric_locale, "Suburb") ~ "Suburb",
          str_detect(degree_of_urbanization_urban_centric_locale, "Town") ~ "Town",
          str_detect(degree_of_urbanization_urban_centric_locale, "Rural") ~ "Rural")) %>%
  mutate(degree_of_urbanization_urban_centric_locale = factor(degree_of_urbanization_urban_centric_locale, levels = c("Rural", "Town", "Suburb", "City"))) %>%
  mutate(quantiles_women = case_when(mean_women %in% (1:24) ~ "0 to 24%",
                                           mean_women %in% (25:49) ~ "25 to 49%",
                                           mean_women %in% (50:74) ~ "50 to 74%",
                                           mean_women %in% (75:100) ~ "75 to 100%")) %>%
  filter(!is.na(quantiles_women)) %>%
  mutate(quantiles_admission = case_when(percent_admitted_total %in% (1:24) ~ "0 to 24%",
                                           percent_admitted_total %in% (25:49) ~ "25 to 49%",
                                           percent_admitted_total %in% (50:74) ~ "50 to 74%",
                                           percent_admitted_total %in% (75:100) ~ "75 to 100%")) %>%
  filter(!is.na(quantiles_admission)) %>%
  select(name, year, undergraduate_enrollment, tuition_and_fees_2018_19, institution_size_category, level_of_institution, degree_of_urbanization_urban_centric_locale, mean_enrollment, mean_african_american, mean_asian, mean_hispanic, mean_white, mean_women, mean_admitted, quantiles_women, quantiles_admission)
# write.csv(mean_data, 'mean_data.csv', row.names = F)

```
