---
title: "Milestone 3"
author: "Emma Freeman"
date: "2/26/2020"
output: html_document
---
Link to Github Repo: https://github.com/emfree19/milestone_3 

## Project Background
This project aims to determine the factors that contribute to the racial and ethnic diversity of college populations. I picked several variables that I wanted to explore: state in which a college is located, size of the institution, level of the institution, degree of urbanization, the admissions rate, and the gender diversity. I hope to use these variables and determine the trends that contribute to highly, racially diverse universities and racially uniform universities. This topic is very central to conversation today with the lawsuit regarding Harvard's admissions practices and conversations regarding affirmative action in news media today.
Furthermore, in additional study of the data, I hope to be able to isolate specific institutions (specifically Ivy League schools) and evaluate the diversity trends especially in response to the recent lawsuit. 

## Data
To accomplish the goal of this project, I have amassed data sets from each year that contain information about almost 7,00 institutions in the continental United States. Each data set contains the information about these institutions in a specific year, and I have collected the data sets from 2009 to 2018. These data sets all come from nces.ed.gov (the Nation Center for Education Statistics).

In addition to these data sets, I have loaded race data from the tidycensus r package in order to compare the mean racial diversity of a set of institutions in a particular state to the general degree of diversity in that state.

## About Me
I am a college freshman at Harvard University, and I plan to study Computer Science. 


