---
title: "Milestone 5"
author: "Emma Freeman"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Libraries necessary for data wrangling and graphic below 

library(tidyverse)
library(dplyr)
library(readr)
library(janitor)
library(stringr)
library(tidycensus)
library(forcats)
library(ggthemes)
```

Link to repo: https://github.com/emfree19/final_project


```{r data wrangling, include = FALSE}

# I made this include = FALSE to remove the pop ups included with the reading 
# and wrangling of data. As I have already inspected these messages, I can now
# conclude that they are unnecessary. 

# I chose to use 2018 data as it is the most recent, and therefore, the most
# pertinent. I can replicate this graphic with any of the years or even with the
# joined data

data_2018 <- read_csv("raw-data//2018_college_data.csv") %>%
  clean_names()
names(data_2018) <- str_replace_all(names(data_2018), "^[^_]*_", "")
names(data_2018) <- str_replace_all(names(data_2018), "_of_undergraduate_enrollment_that_are", "")

# This takes data from the tidycensus library and gives population estimates 
# for different races in the United States circa the year 2010

census_data_2 <- get_acs(geography = "us", 
                         variables = c(
                           total_pop = "B01001_001",
                           pop_white = "B01001A_001",
                           pop_african_american = "B01001B_001",
                           pop_native_american_alaskan = "B01001C_001",
                           pop_asian = "B01001D_001",
                           pop_native_hawaiian_pacific_islander = "B01001E_001",
                           pop_other = "B01001F_001",
                           pop_two_or_more_races = "B01001G_001"),
                         year = 2010) 

# I pivoted wider, so that I could use the population variables and calculate
# the percent of the population that each race holds 

census_data_2 <- census_data_2 %>%
  select(variable, estimate) %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  mutate(pct_white = (pop_white / total_pop) * 100) %>%
  mutate(pct_african_american = (pop_african_american / total_pop) * 100) %>%
  mutate(pct_native_american_alaskan = (pop_native_american_alaskan / total_pop) * 100) %>%
  mutate(pct_asian = (pop_asian / total_pop) * 100) %>%
  mutate(pct_native_hawaiian_pacific_islander = (pop_native_hawaiian_pacific_islander / total_pop) * 100) %>%
  mutate(pct_other = (pop_other / total_pop) * 100) %>%
  mutate(pct_two_or_more_races = (pop_two_or_more_races / total_pop) * 100)
```

```{r}

# This removes the institutions that either did not report a size category or 
# it was not applicable because there is no bosplot for these items 

size_2018 <- data_2018 %>%
  
  # The institution size variable must be a factor, so that they can be used as
  # the variable on the x-axis of a box plot
  
  mutate(institution_size_category = factor(institution_size_category,
                                            levels = c("Under 1,000",
                                                       "1,000 - 4,999",
                                                       "5,000 - 4,999", 
                                                       "10,000 - 19,999",
                                                       "20,000 and above",
                                                       "Not applicable",
                                                       "Not reported"))) %>%
  filter(institution_size_category != "Not applicable" & institution_size_category != "Not reported") 
  
aa_plot_2018 <- size_2018 %>%
  
  # This removes any NA observations in order to remove the message about the
  # removal of NA observations that occurs when the geom_boxplot() is used
  
  filter(!is.na(percent_black_or_african_american)) %>%
  ggplot(aes(x = as_factor(institution_size_category), y = percent_black_or_african_american)) +
  
  # This shows the decreasing number of items toward the extremes 
  
  geom_boxplot(alpha = 0.25) +
  xlab("Size of Institution") + 
  ylab("Percent Black or African American") +
  
  # I will use them_tufte going forward, so that my final project appears 
  # consistent
  
  theme_tufte() + 
  labs(title = "Percent of Black or African Students by Size of Institution",
       subtitle = "With comparison at national population estimate") +
  theme(axis.line = element_line()) +
  
  # This gives the national estimate for the percentage of the population that 
  # is African American, offering a comparison for the level of representation 
  # in schools 
  
  geom_hline(yintercept = census_data_2$pct_african_american, color = "red")
aa_plot_2018
```
```{r}
asian_plot_2018 <- size_2018 %>%
  
  # This removes any NA observations in order to remove the message about the
  # removal of NA observations that occurs when the geom_boxplot() is used
  
  filter(!is.na(percent_black_or_african_american)) %>%
  ggplot(aes(x = as_factor(institution_size_category), y = percent_asian)) +
  
  # This shows the decreasing number of items toward the extremes 
  
  geom_boxplot(alpha = 0.25) +
  xlab("Size of Institution") + 
  ylab("Percent Asian") +
  
  # I will use them_tufte going forward, so that my final project appears 
  # consistent
  
  theme_tufte() + 
  labs(title = "Percent of Asian Students by Size of Institution",
       subtitle = "With comparison at national population estimate") +
  theme(axis.line = element_line()) +
  
  # This gives the national estimate for the percentage of the population that 
  # is African American, offering a comparison for the level of representation 
  # in schools 
  
  geom_hline(yintercept = census_data_2$pct_asian, color = "red")
asian_plot_2018
```

